{
  "schema_version": "1.4.0",
  "id": "GHSA-5m8f-chrv-7rw5",
  "modified": "2021-11-19T13:19:43Z",
  "published": "2021-11-23T18:04:47Z",
  "aliases": [
    "CVE-2021-43668"
  ],
  "summary": "Denial of Service in Go-Ethereum",
  "details": "Go-Ethereum 1.10.9 nodes crash (denial of service) after receiving a serial of messages and cannot be recovered. They will crash with \"runtime error: invalid memory address or nil pointer dereference\" and arise a SEGV signal.",
  "severity": [

  ],
  "affected": [
    {
      "package": {
        "ecosystem": "Go",
        "name": "github.com/ethereum/go-ethereum"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "last_affected": "1.10.9"
            }
          ]
        }
      ]
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2021-43668"
    },
    {
      "type": "WEB",
      "url": "https://github.com/ethereum/go-ethereum/issues/23866"
    },
    {
      "type": "WEB",
      "url": "https://github.com/syndtr/goleveldb/issues/373"
    },
    {
      "type": "PACKAGE",
      "url": "https://github.com/ethereum/go-ethereum"
    }
  ],
  "database_specific": {
    "cwe_ids": [
      "CWE-476"
    ],
    "severity": "MODERATE",
    "github_reviewed": true,
    "github_reviewed_at": "2021-11-19T13:19:43Z",
    "nvd_published_at": "2021-11-18T16:15:00Z"
  }
}