{
  "schema_version": "1.4.0",
  "id": "GHSA-29vr-79w7-p649",
  "modified": "2022-09-06T20:58:16Z",
  "published": "2022-03-11T00:02:00Z",
  "aliases": [
    "CVE-2021-44597"
  ],
  "summary": "Incorrect Authorization in Gerapy",
  "details": "An Access Control vunerabiity exists in Gerapy v 0.9.7 via the spider parameter in project_configure function.",
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H"
    }
  ],
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "gerapy"
      },
      "ecosystem_specific": {
        "affected_functions": [
          "gerapy.server.core.views.project_clone",
          "gerapy.server.core.views.project_configure"
        ]
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "0.9.8"
            }
          ]
        }
      ]
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2021-44597"
    },
    {
      "type": "WEB",
      "url": "https://github.com/Gerapy/Gerapy/issues/219"
    },
    {
      "type": "WEB",
      "url": "https://github.com/Gerapy/Gerapy/commit/49bcb19be5e0320e7e1535f34fe00f16a3cf3b28"
    },
    {
      "type": "PACKAGE",
      "url": "https://github.com/Gerapy/Gerapy"
    },
    {
      "type": "WEB",
      "url": "https://github.com/Gerapy/Gerapy/releases/tag/v0.9.8"
    },
    {
      "type": "WEB",
      "url": "https://github.com/pypa/advisory-database/tree/main/vulns/gerapy/PYSEC-2022-228.yaml"
    }
  ],
  "database_specific": {
    "cwe_ids": [
      "CWE-863"
    ],
    "severity": "CRITICAL",
    "github_reviewed": true,
    "github_reviewed_at": "2022-03-28T14:23:45Z",
    "nvd_published_at": "2022-03-10T21:15:00Z"
  }
}